### ISSUE TITLE
Question about license and contribution

### ISSUE THREAD

**Issue by alx3dev** [ademdc/ruby-vibe#1]
Hello, I see there's no license in this repository. I made a fork and added MIT license like stated in `.gemspec`, because I would like to refactor it and to add a few more methods, so i can use it. Is that ok?

**Comment by ademdc** [comment]
Hi @alx3dev! Thanks for the question.

Sure thing. When you finish you can also make a PR to add these changes to this repo.

Cheers

**Comment by alx3dev** [comment]
Sure, I will. For now, I simplified message.rb and info.rb. I will upload it once I am done, and make PR once I test it, since I need it for production use.

**Comment by alx3dev** [comment]
Here you can see what I did so far. I removed modules and made classes. Client is responsible to handle token, name avatar and to send viber request. RubyVibe extend Client, so user methods stay there, and they call `viberize` with arguments.
Method `viberize` is private, responsible for:
 - first argument is viber `API url` -> stay in URL module `(URL::SEND_MESSAGE)`
 - it also accept `options hash` - that is added to payload hash
 - if `info: true` argument is added, payload is created without name and avatar  
  
Still work on that, plan to write some tests tomorrow.   
https://github.com/alx3dev/ruby-vibe

**Comment by ademdc** [comment]
All that looks good. (y)
